#=====================================================================================
# https://github.com/ophub/amlogic-s9xxx-openwrt
# Description: Build OpenWrt Docker image
# Instructions: https://github.com/docker/build-push-action
# Build and Push to: https://hub.docker.com/
#=====================================================================================

name: Build OpenWrt Docker image

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      source_branch:
        description: "Select the source branch"
        required: false
        default: "official"
        type: choice
        options:
          - official
          - lede
          - immortalwrt
      docker_img:
        description: "Set the docker image"
        required: false
        default: "ophub/openwrt-armv8:latest"
        type: choice
        options:
          - ophub/openwrt-armv8:latest
          - ophub/openwrt-aarch64:latest

env:
  TZ: America/New_York
  MAKE_DOCKER_SH: config/docker/make_docker_image.sh
  DOCKER_OUTPATH: out

jobs:
  build:
    runs-on: ubuntu-22.04-arm
    if: ${{ github.event.repository.owner.id }} == ${{ github.event.sender.id }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download OpenWrt rootfs file [ ${{ inputs.source_branch }} ]
        id: down
        if: (!cancelled())
        run: |
          # Get OpenWrt file
          openwrt_url="$(curl \
                            --header "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                            -s "https://api.github.com/repos/${GITHUB_REPOSITORY}/releases?per_page=100" |
                            grep -o "OpenWrt_.*${{ inputs.source_branch }}.*/.*rootfs.tar.gz" |
                            sort -urV |
                            head -n 1
                        )"
          [[ -z "${openwrt_url}" ]] && echo -e "OpenWrt file not found!" && exit 1

          [[ -d "openwrt" ]] || mkdir -p openwrt
          curl -fsSL "https://github.com/${GITHUB_REPOSITORY}/releases/download/${openwrt_url}" -o "openwrt/openwrt-armsr-armv8-generic-rootfs.tar.gz"
          # curl -fsSL "https://github.com/${GITHUB_REPOSITORY}/releases/download/${openwrt_url}" -o "openwrt/openwrt-armvirt-64-default-rootfs.tar.gz"
          echo "https://github.com/${GITHUB_REPOSITORY}/releases/download/${openwrt_url}"
          [[ "${?}" -ne "0" ]] && echo "OpenWrt file download failed." && exit 1
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Build the Docker image
        id: make
        if: ${{ steps.down.outputs.status }} == 'success' && !cancelled()
        run: |
          chmod +x ${MAKE_DOCKER_SH}
          ${MAKE_DOCKER_SH}
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Set up Docker Buildx
        id: buildx
        if: (!cancelled())
        uses: docker/setup-buildx-action@v3

      - name: Login to Aliyun Container Registry
        run: |
          echo ${{ secrets.ALIYUN_REPO_PASS }} | docker login \
            -u ${{ secrets.ALIYUN_REPO_USER }} \
            --password-stdin \
            ${{ secrets.ALIYUN_REPO_DOMAIN }}
            
      # 步骤3：构建并推送 Docker 镜像
      # https://hub.docker.com/r/ophub/openwrt-aarch64
      - name: Build and Push Docker Image
        run: |
          cd ${{ env.DOCKER_OUTPATH }}
          docker buildx version
          docker buildx create --use
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker buildx build --platform linux/arm64 -t ${{ secrets.ALIYUN_REPO_DOMAIN }}/homesmart/openwrt:latest --push .
          docker images
